version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: liveroom_db
      POSTGRES_USER: liveroom_user
      POSTGRES_PASSWORD: liveroom_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
